language: csharp
solution: ink.sln
install:
  - sudo apt-get install nunit-console
  
before_script:
  - nuget restore ink.sln
script:
  - xbuild ink.sln
  - nunit-console tests/bin/Debug/ink-tests.dll